/*
 * Copyright 2010-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.client.builder;

import java.util.concurrent.ExecutorService;
import software.amazon.awssdk.annotation.ReviewBeforeRelease;

/**
 * This includes required and optional override configuration required by every async client builder. An instance can be acquired
 * by calling the static "builder" method on the type of async client you wish to create.
 *
 * <p>Implementations of this interface are mutable and not thread-safe.</p>
 *
 * @param <B> The type of builder that should be returned by the fluent builder methods in this interface.
 * @param <C> The type of client generated by this builder.
 */
public interface AsyncClientBuilder<B extends AsyncClientBuilder<B, C>, C>
        extends ClientBuilder<B, C> {
    /**
     * Configure the executor service provider that generates {@link ExecutorService} instances for calling AWS asynchronously.
     * A new {@link ExecutorService} will be created from this provider each time {@link ClientBuilder#build()} is invoked.
     */
    @ReviewBeforeRelease("When we switch to use NIO, this configuration will likely change. If not, comment it better.")
    B asyncExecutorProvider(ExecutorProvider asyncExecutorProvider);
}
