version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      # Ignore test dependencies to reduce PR noisiness. We don't need to stay
      # on top of them as much as compile/runtime dependencies
      - dependency-name: "com.amazonaws:aws-java-sdk*"
      - dependency-name: "com.amazonaws:aws-java-sdk*"
      - dependency-name: "com.github.tomakehurst:*"
      - dependency-name: "org.mockito:*"
      - dependency-name: "nl.jqno.equalsverifier:*"
      - dependency-name: "org.assertj:*"
      - dependency-name: "com.google.guava:*"
      - dependency-name: "org.junit.jupiter:*"
      - dependency-name: "junit:*"
      - dependency-name: "org.testng:*"
      - dependency-name: "org.hamcrest:*"
      - dependency-name: "com.almworks.sqlite4java:*"
      - dependency-name: "org.eclipse.jetty:*"
      - dependency-name: "javax.servlet:*"
      # Maven/build system updates don't have to track very latest. Again, to
      # reduce noisiness
      - dependency-name: "org.apache.maven.plugins:*"
      - dependency-name: "org.sonatype.plugins:*"