version: 0.2

phases:
  install:
    runtime-versions:
      java: "$JAVA_RUNTIME"

  build:
    commands:
      - mvn install -P quick -pl :sdk-benchmarks --am
      - mvn install -pl :bom-internal
      - cd test/sdk-benchmarks
      - java -jar target/benchmarks.jar -f 1 -wi 8 -i 8 software.amazon.awssdk.benchmark.enhanced.dynamodb
